<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Employee;
use App\Models\Template;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::updateOrCreate(['email' => 'Qettaribadr@gmail.com'], ['name' => 'Responsable RH', 'first_name' => 'BADR', 'password' => bcrypt('0000'), 'role' => 'responsable']);
        User::updateOrCreate(['email' => 'ahmed.mhaira@uit.ac.ma'], ['name' => 'Agent RH', 'first_name' => 'AHMED', 'password' => bcrypt('0000'), 'role' => 'agent']);

        Employee::create(['first_name' => 'Ahmed', 'last_name' => 'Benali', 'civilite' => 'M.', 'email' => 'ahmed.benali@hs-infra.ma', 'phone' => '0612345678', 'genre' => 'Masculin', 'nationalite' => 'Marocaine', 'ville' => 'Tanger', 'position' => 'Développeur', 'department' => 'IT', 'agence' => 'Tanger', 'hire_date' => '2023-01-15', 'salary' => '15000', 'birth_date' => '1995-04-12', 'birth_place' => 'Tanger', 'cin' => 'GN258778', 'cnss' => '254878795', 'bank_type' => 'Banque Populaire', 'rib' => '007 000 010000000000000000', 'bank_type_pro' => 'Banque Populaire Pro', 'rib_pro' => '007 001 010000000000000000']);
        Employee::create(['first_name' => 'Fatima', 'last_name' => 'Zahra', 'civilite' => 'Mme', 'email' => 'fatima.zahra@hs-infra.ma', 'phone' => '0623456789', 'genre' => 'Féminin', 'nationalite' => 'Marocaine', 'ville' => 'Casablanca', 'position' => 'Comptable', 'department' => 'Finance', 'agence' => 'Casablanca', 'hire_date' => '2022-06-01', 'salary' => '12000', 'birth_date' => '1998-09-25', 'birth_place' => 'Casablanca', 'cin' => 'GN345678', 'cnss' => '345678901', 'bank_type' => 'CIH', 'rib' => '007 000 020000000000000000', 'bank_type_pro' => 'CIH Pro', 'rib_pro' => '007 001 020000000000000000']);
        Employee::create(['first_name' => 'Hassan', 'last_name' => 'El Khadir', 'civilite' => 'M.', 'email' => 'hassan.elkhadir@hs-infra.ma', 'phone' => '0634567890', 'genre' => 'Masculin', 'nationalite' => 'Marocaine', 'ville' => 'Tanger', 'position' => 'Responsable RH', 'department' => 'RH', 'agence' => 'Tanger', 'hire_date' => '2021-03-20', 'salary' => '20000', 'birth_date' => '1990-11-03', 'birth_place' => 'Fès', 'cin' => 'GN456789', 'cnss' => '456789012', 'bank_type' => 'BMCE', 'rib' => '007 000 030000000000000000', 'bank_type_pro' => 'BMCE Pro', 'rib_pro' => '007 001 030000000000000000']);

        $templates = [
            [1, 'Attestation de travail', 'Attestation de travail', true, "ATTESTATION DE TRAVAIL\n\nJe soussigné, M. BADR Qettari, né le 12/02/1990, Responsable des Ressources Humaines de la société HS-INFRA — Agence Barid Bank — RIB : 007 000 000000000000000000, ayant son siège social à Tanger (Maroc),\n\nAtteste par la présente que :\n\n{{civilite}} {{first_name}} {{last_name}}\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nGenre : {{genre}}\nNationalité : {{nationalite}}\nVille : {{ville}}\nExerçant la fonction de {{position}}\nDépartement : {{department}} — Agence : {{agence}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nLa présente attestation est délivrée à l'intéressé(e) sur sa demande pour servir et valoir ce que de droit.\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet : M. BADR Qettari\nResponsable des Ressources Humaines\nNé le 12/02/1990 à Tanger"],
            [2, 'Attestation de salaire', 'Attestation de salaire', true, "ATTESTATION DE SALAIRE\n\nJe soussigné, M. BADR Qettari, né le 12/02/1990, Responsable des Ressources Humaines de la société HS-INFRA — Agence Barid Bank — RIB : 007 000 000000000000000000,\n\nAtteste que {{civilite}} {{first_name}} {{last_name}}\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nGenre : {{genre}}\nNationalité : {{nationalite}}\nVille : {{ville}}\nExerçant la fonction de {{position}}\nDépartement : {{department}} — Agence : {{agence}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nPerçoit un salaire mensuel brut de : {{salary}} DH\n\nLa présente attestation est délivrée à l'intéressé(e) pour tous usages légaux.\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet : M. BADR Qettari\nResponsable des Ressources Humaines\nNé le 12/02/1990 à Tanger"],
            [3, 'Demande de prime', 'Demande de prime', true, "DEMANDE DE PRIME\n\nInformations du demandeur :\n\nNom & Prénom : {{first_name}} {{last_name}}\nFonction : {{position}}\nDépartement : {{department}}\nAgence : {{agence}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nMotif :\n{{motif}}\n\nMontant accordé :\n{{montant}} DH\n\nSIGNATURE\n\nDemandeur : ______________________\nResponsable hiérarchique : ______________________\nDépartement RH : ______________________\nDirection Générale : ______________________"],
            [4, 'Certificat médical', 'Certificat médical', true, "CERTIFICAT MÉDICAL\n\nJe soussigné, Docteur ______________________, certifie avoir examiné {{civilite}} {{first_name}} {{last_name}}.\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\n\nRésultat :\n\n\n\nArrêt de travail du ______________ au ______________\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet du médecin : ______________________"],
            [5, 'Demande d\'avance', 'Demande d\'avance', true, "DEMANDE D'AVANCE\n\nMadame/Monsieur le Responsable RH,\n\nJe soussigné(e) {{first_name}} {{last_name}}, exerçant la fonction de {{position}} au sein du département {{department}} (Agence : {{agence}}) — CIN : {{cin}} — CNSS : {{cnss}} — Type agence : {{bank_type}} — RIB : {{rib}}, sollicite une avance sur salaire d'un montant de {{montant}} DH.\n\nMotif : {{motif}}\n\nJe m'engage à rembourser cette avance selon les modalités convenues avec l'administration.\n\nSignature du demandeur : ______________________\nAvis du responsable hiérarchique : ______________________\nDécision RH : ______________________"],
            [6, 'Certificat de travail', 'Certificat de travail', true, "CERTIFICAT DE TRAVAIL\n\nJe soussigné, M. BADR Qettari, né le 12/02/1990, Responsable des Ressources Humaines de la société HS-INFRA — Agence Barid Bank — RIB : 007 000 000000000000000000,\n\nCertifie que {{civilite}} {{first_name}} {{last_name}}\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nGenre : {{genre}}\nNationalité : {{nationalite}}\nVille : {{ville}}\nExerçant la fonction de {{position}}\nDépartement : {{department}} — Agence : {{agence}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nA été employé(e) dans notre société du ______________ au ______________\nDurée totale : ______________\nDernier salaire perçu : {{salary}} DH\n\nCe certificat est délivré à l'intéressé(e) pour servir et valoir ce que de droit.\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet : M. BADR Qettari\nResponsable des Ressources Humaines\nNé le 12/02/1990 à Tanger"],
            [7, 'Attestation de domiciliation irrévocable de salaire', 'Attestation de domiciliation irrévocable de salaire', true, "ATTESTATION DE DOMICILIATION IRRÉVOCABLE DE SALAIRE\n\nJe soussigné(e) {{first_name}} {{last_name}}\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nExerçant la fonction de {{position}} — Agence : {{agence}}\n\nDéclare par la présente domicilier mon salaire de façon irrévocable auprès de la banque :\n\nType agence : {{bank_type}} — RIB : {{rib}}\n\nMontant mensuel domicilié : {{salary}} DH\n\nJe reconnais que cette domiciliation reste irrévocable pendant toute la durée de mon contrat de travail.\n\nFait à Tanger, le {{date}}\n\nSignature de l'employé(e) : ______________________\nCachet de la banque : ______________________"],
            [8, 'Demande d\'aide sociale', 'Demande d\'aide sociale', true, "DEMANDE D'AIDE SOCIALE\n\nObjet : Demande d'aide sociale\n\nMadame/Monsieur le Responsable RH,\n\nJe soussigné(e) {{first_name}} {{last_name}}, matricule ______________, exerçant la fonction de {{position}} au département {{department}}, agence {{agence}} — CIN : {{cin}} — CNSS : {{cnss}} — Type agence : {{bank_type}} — RIB : {{rib}}, ai l'honneur de solliciter votre bienveillance pour une aide sociale.\n\nMotif de la demande :\n{{motif}}\n\nMontant sollicité : {{montant}} DH\n\nPièces jointes :\n- ______________\n- ______________\n\nSignature du demandeur : ______________________\nAvis du responsable : ______________________\nDécision de la commission : ______________________"],
            [9, 'Pièce de caisse dépense', 'Pièce de caisse dépense', true, "PIÈCE DE CAISSE DÉPENSE\n\nN° : ______________\nDate : {{date}}\n\nNom du bénéficiaire : {{first_name}} {{last_name}}\nFonction : {{position}}\n\nObjet de la dépense : {{motif}}\n\nMontant : {{montant}} DH\n\nArrêté la présente pièce à la somme de : ______________ DH\n\nSignatures :\n\nLe bénéficiaire : ______________________\nLe responsable : ______________________\nLe comptable : ______________________\nLe caissier : ______________________"],
            [10, 'Demande prime', 'Demande prime', true, "DEMANDE DE PRIME\n\nMadame/Monsieur le Responsable,\n\nJe soussigné(e) {{first_name}} {{last_name}}, {{position}} — CIN : {{cin}} — CNSS : {{cnss}} — Type agence : {{bank_type}} — RIB : {{rib}}, ai l'honneur de solliciter l'octroi d'une prime pour le motif suivant :\n\n{{motif}}\n\nMontant sollicité : {{montant}} DH\n\nSignature du demandeur : ______________________\nAvis du supérieur hiérarchique : ______________________\nDécision de la direction : ______________________"],
            [11, 'Attestation de travail et salaire', 'Attestation de travail et salaire', true, "ATTESTATION DE TRAVAIL ET SALAIRE\n\nJe soussigné, M. BADR Qettari, né le 12/02/1990, Responsable des Ressources Humaines de la société HS-INFRA — Agence Barid Bank — RIB : 007 000 000000000000000000,\n\nAtteste que {{civilite}} {{first_name}} {{last_name}}\nNé(e) le {{birth_date}} à {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nGenre : {{genre}}\nNationalité : {{nationalite}}\nVille : {{ville}}\nExerçant la fonction de {{position}}\nDépartement : {{department}} — Agence : {{agence}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nEst employé(e) à notre société depuis le {{hire_date}}\nSalaire mensuel actuel : {{salary}} DH\n\nCette attestation est délivrée à l'intéressé(e) pour tous usages légaux.\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet : M. BADR Qettari\nResponsable des Ressources Humaines\nNé le 12/02/1990 à Tanger"],
            [12, 'Attestation de travail en bonne et due forme', 'Attestation de travail en bonne et due forme', true, "ATTESTATION DE TRAVAIL EN BONNE ET DUE FORME\n\nJe soussigné, M. BADR Qettari, né le 12/02/1990, Responsable des Ressources Humaines de la société HS-INFRA — Agence Barid Bank — RIB : 007 000 000000000000000000, ayant son siège social à Tanger (Maroc),\n\nAtteste par la présente que {{civilite}} {{first_name}} {{last_name}}\n\nNé(e) le : {{birth_date}}\nLieu de naissance : {{birth_place}}\nCIN : {{cin}}\nCNSS : {{cnss}}\nGenre : {{genre}}\nNationalité : {{nationalite}}\nVille : {{ville}}\nExerçant la fonction de : {{position}}\nDépartement : {{department}} — Agence : {{agence}}\nType agence : {{bank_type}} — RIB : {{rib}}\n\nEmployé(e) sous le matricule : ______________\n\nLa présente attestation est délivrée à l'intéressé(e) sur sa demande pour servir et valoir ce que de droit.\n\nFait à {{ville}}, le {{date}}\n\nSignature et cachet : M. BADR Qettari\nResponsable des Ressources Humaines\nNé le 12/02/1990 à Tanger"],
        ];

        foreach ($templates as $t) {
            Template::insertOrIgnore(['id' => $t[0], 'title' => $t[1], 'type' => $t[2], 'is_active' => $t[3], 'content' => $t[4], 'created_at' => now(), 'updated_at' => now()]);
        }
    }
}
